# Generated by Django 4.2.7 on 2024-03-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='tag',
            field=models.ManyToManyField(to='post.tag'),
        ),
    ]
