# Generated by Django 4.2.7 on 2024-03-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_pin_pin_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='pin_tag',
            field=models.ManyToManyField(blank=True, related_name='post_tag', to='post.tag'),
        ),
    ]
